add eink-light theme
streetwriters/notesnook-themes pull request #64
Opened 2024-01-14 20:30 UTC by Tsyron

I made an e-ink theme

2024-01-15 08:45 UTC, thecodrr requested changes

2024-01-15 08:45 UTC, thecodrr commented on themes/eink-light/v1/eink-light
@Tsyron you need to give the theme `.json` extension.

2024-01-15 10:51 UTC, Tsyron commented on themes/eink-light/v1/eink-light
oh sorry, I didn't see that. I've changed the name

2024-01-15 11:17 UTC, thecodrr requested changes

2024-01-15 11:17 UTC, thecodrr commented on themes/eink-light/v1/eink-light.json
Forgot to mention, the theme file must be named `theme.json`.

2024-01-16 20:05 UTC, Tsyron commented
yes, this is true, but text that's slightly grey is hard to read on e-ink

2024-01-20 04:53 UTC, thecodrr commented
What do you think @Starship-Headlight? Can we make the text black in your `LIGHT & DARK` theme? Both of these themes are identical aside from the text color.

2024-07-16 13:37 UTC, closed without merging