Feat: update Tokyonight theme to Tokyonight Moon and add Tokyonight Day variant
streetwriters/notesnook-themes pull request #89
Opened 2024-07-28 01:27 UTC by echoriiku

- Updated the Tokyonight theme to the Tokyonight Moon variant
- Added a new variant, Tokyonight Day, following the namescheme of the Tokyonight project
- I think this fixes https://github.com/streetwriters/notesnook-themes/issues/82

2024-07-28 01:40 UTC, echoriiku commented
Is it failing because I changed the theme folder name? It's using the correct namescheme now

2024-07-29 04:54 UTC, thecodrr requested changes
Why the formatting changes?

2024-07-29 09:32 UTC, echoriiku commented
I was annoyed because my changes didn’t work at first. So, I threw the code into a `JSON` formatter, hoping it would fix some mistake I couldn’t find.

2024-07-29 10:07 UTC, echoriiku reviewed
Sorry for the unwanted changes, all good

2024-07-29 12:54 UTC, echoriiku reviewed
used the theme builder to correct the unintended formatting changes

2024-07-30 04:52 UTC, thecodrr requested changes

2024-07-30 04:52 UTC, thecodrr commented on themes/tokyonight-moon/v1/code-block.css
I think you should run this through a formatter like https://www.cleancss.com/css-beautify/

2024-07-30 04:52 UTC, thecodrr commented on themes/tokyonight-day/v1/code-block.css
I think you should run this through a formatter like https://www.cleancss.com/css-beautify/

2024-07-30 05:07 UTC, thecodrr commented
@echoriiku You can't change the id or the directory name for a theme. Since the id is internal, you can leave it be and simply change the title etc. If that doesn't work, you can just create a new theme with the new id.

2024-07-30 06:47 UTC, echoriiku reviewed
reverted the ID changes

2024-07-30 06:49 UTC, thecodrr approved these changes

2024-07-30 06:50 UTC, merged